### ISSUE TITLE
Dead link to the list of built-in entities

### ISSUE THREAD

**Issue by Mandorlo** [leon-ai/docs.getleon.ai#13]
Hi,
The link to the built-in entities is dead:  [this link](https://github.com/axa-group/nlp.js/blob/master/docs/builtin-entity-extraction.md), could you update it ?

**Comment by ThomasRitaine** [comment]
Hi !

The new link is :
[https://github.com/axa-group/nlp.js/blob/master/docs/v3/builtin-entity-extraction.md](https://github.com/axa-group/nlp.js/blob/master/docs/v3/builtin-entity-extraction.md)

**Comment by louistiti** [comment]
Hello @Mandorlo and @ThomasRitaine :wave:,

I know it's a bit late, but I'm finally working again on Leon.

The link has been fixed in https://github.com/leon-ai/docs.getleon.ai/commit/ed30138093646be3d630afce20b72003bfad1bd6.

Thanks for pointing it and for providing the new link.
