### ISSUE TITLE
Installing @leon-ai/cli creates a leon birth, no need for second command

### ISSUE THREAD

**Issue by Briscoooe** [leon-ai/docs.getleon.ai#137]
[The docs](https://docs.getleon.ai/#install-the-leon-cli) insist that the commands to install leon are

```
$ npm install --global @leon-ai/cli
$ leon create birth
```

However, running the first command outputs this

```
✔ Installing packages
✔ Installing Python
✔ Downloading Leon source code
✔ Installing npm dependencies
✔ Building Leon core

Success: Leon is born! 🎉
You can start your leon instance:
exec $SHELL
leon start
```

Which runs the `leon create birth` command in the background. If you run the second command after install, you get this

```
$ leon create birth
Error: /Users/briscoooe/.leon already exists, please provide another path.
```

[This page in the docs](https://docs.getleon.ai/#install-the-leon-cli) and [the landing page](https://getleon.ai/) (under "Be the owner of your Leon, today") need to be updated to remove the suggestion of the second command

**Comment by louistiti** [comment]
The first command installs the Leon CLI and does not create any Leon instance. The second command creates a Leon instance via the CLI.
If you get this error message, it means that you have already ran `leon create birth` earlier.
