### ISSUE TITLE
Broken Link on Introduction Page of Documentation to 1.0.0-beta.7+dev 

### ISSUE THREAD

**Issue by LyZet** [leon-ai/docs.getleon.ai#140]
Hello, 
at the bottom of the page https://docs.getleon.ai/ on the Introduction page there is a tool tip: 
`To see what he can do, please refer to the [packages list](https://github.com/leon-ai/leon/tree/master/packages).`
Clicking on the link [packages list](https://github.com/leon-ai/leon/tree/master/packages) leads to a "Page not found" error message. 

This is my first issue ever, trying to contribute to hacktoberfest. Feedback is welcome!

**Comment by louistiti** [comment]
Thanks, it has been fixed in https://github.com/leon-ai/docs.getleon.ai/commit/0bed85193de53e4469a23cfb234355d733060a77.
