### ISSUE TITLE
Grammatical Errors on Glossary Page in Docs

### ISSUE THREAD

**Issue by Radhika403** [leon-ai/docs.getleon.ai#142]
On the Glossary page, under the "Actions" heading the very first statement says - "Actions represent the modules entry points." 
Modules here should have an **'s** instead.

Also under Packages on the same page, it should be **data for better scalability** instead of "data for a better scalability".

**Comment by Radhika403** [comment]
PR -> https://github.com/leon-ai/docs.getleon.ai/pull/141

**Comment by louistiti** [comment]
Thanks, it is merged.
