### ISSUE TITLE
Add WebSockets in Glossary

### ISSUE THREAD

**Issue by co16353sidak** [leon-ai/docs.getleon.ai#3]
When working on PR #2,
I wanted to link WebSockets in the text so I had to link the MDN documentation but it would be better if we add a small description of it inside the Glossary and then link it to the former article (like we are doing with every other definition inside articles.)

Would also love to work on this.

**Comment by louistiti** [comment]
Hello @co16353sidak,

Thanks for suggesting. However, I assume readers already know about WebSockets when they plan to use or contribute to Leon.
